package Conversion;

import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Interfaz gráfica para la conversión de AFND a AFD.
 * Proporciona tablas para mostrar el AFND y el AFD, campos de texto
 * y botones para agregar/eliminar estados y letras, así como
 * para validar y convertir el autómata.
 * 
 * La clase delega la lógica de operación al {@link Controlador} asociado.
 * La mayor parte de la interfaz fue generada por NetBeans GUI Builder.
 * 
 * Componentes accesibles públicamente mediante getters:
 * - Botones: btnAccion, btnConvertir, btnValidar
 * - Tablas: tblAFND, tblAFD
 * - Campo de texto: txtInsertarTexto
 * - Etiqueta de acción: lblAccion
 * - ComboBox de acciones: cbxAFND
 * 
 * Uso:
 * 1. Crear la instancia de Vista.
 * 2. Interactuar con los componentes; las acciones son delegadas al controlador.
 * 3. Mostrar la ventana mediante `setVisible(true)`.
 * 
 * @author Kevin
 */
public class Vista extends javax.swing.JFrame {

    
    private Controlador c;
    /**
 * Crea la ventana principal de la aplicación e inicializa
 * todos los componentes gráficos.
 * También crea e inicializa el {@link Controlador} asociado.
 */
    public Vista() {
        initComponents();
        c = new Controlador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxAFND = new javax.swing.JComboBox<>();
        scroll1 = new javax.swing.JScrollPane();
        tblAFND = new javax.swing.JTable();
        lblAccion = new javax.swing.JLabel();
        txtInsertarTexto = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();
        btnValidar = new javax.swing.JButton();
        btnConvertir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        scroll2 = new javax.swing.JScrollPane();
        tblAFD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("AFND");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("CONVERSION ANFD -> AFD");

        cbxAFND.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblAFND.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAFND.setMinimumSize(new java.awt.Dimension(300, 80));
        scroll1.setViewportView(tblAFND);

        lblAccion.setText("Agregar Estado:");

        txtInsertarTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInsertarTextoKeyPressed(evt);
            }
        });

        btnAccion.setText(">");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnConvertir.setText("Convertir");
        btnConvertir.setEnabled(false);
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("AFD");

        tblAFD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll2.setViewportView(tblAFD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxAFND, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblAccion)
                        .addGap(18, 18, 18)
                        .addComponent(txtInsertarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConvertir)
                        .addGap(50, 50, 50))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(235, 235, 235)
                    .addComponent(jLabel2)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxAFND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccion)
                    .addComponent(txtInsertarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccion)
                    .addComponent(btnValidar)
                    .addComponent(btnConvertir))
                .addGap(33, 33, 33)
                .addComponent(scroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel2)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Evento del botón Validar: delega la acción al controlador.
 */
    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        c.validarAFND();
    }//GEN-LAST:event_btnValidarActionPerformed
/**
 * Evento del botón Accion: delega la acción al controlador.
 */

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        c.realizarAccion();
    }//GEN-LAST:event_btnAccionActionPerformed
    /**
 * Evento de presionar Enter en el campo de texto: simula clic en btnAccion.
 */
    private void txtInsertarTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInsertarTextoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Aquí va la acción que quieres ejecutar
            System.out.println("Presionaste ENTER");
            btnAccion.doClick(); // opcional, simula clic del botón
        }
    }//GEN-LAST:event_txtInsertarTextoKeyPressed

    /**
 * Evento del botón Convertir: llena la tabla AFD usando el controlador.
 */
    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        c.llenarTablaAFD();
    }//GEN-LAST:event_btnConvertirActionPerformed

    public JButton getBtnAccion() {
        return btnAccion;
    }

    public JButton getBtnConvertir() {
        return btnConvertir;
    }

    public JButton getBtnValidar() {
        return btnValidar;
    }

    public JTable getTblAFD() {
        return tblAFD;
    }

    public JTextField getTxtInsertarTexto() {
        return txtInsertarTexto;
    }

    public JTable getTblAFND() {
        return tblAFND;
    }

    public JLabel getLblAccion() {
        return lblAccion;
    }

    public JComboBox<String> getCbxAFND() {
        return cbxAFND;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnValidar;
    private javax.swing.JComboBox<String> cbxAFND;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JScrollPane scroll1;
    private javax.swing.JScrollPane scroll2;
    private javax.swing.JTable tblAFD;
    private javax.swing.JTable tblAFND;
    private javax.swing.JTextField txtInsertarTexto;
    // End of variables declaration//GEN-END:variables
}
